package jkt.centralisateur.storage.model;

// Generated by Hibernate Tools 3.2.4.GA

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * News generated by hbm2java
 */
@Entity
@Table(name = "news", catalog = "centralisateur")
public class News implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	static public final String _id = "id";
	static public final String _horodatage = "horodatage";
	static public final String _text = "text";

	private long id;
	private Date horodatage;
	private String text;

	public News() {
	}

	public News(long id, Date horodatage, String text) {
		this.id = id;
		this.horodatage = horodatage;
		this.text = text;
	}

	@Id
	/*BasicAnnotation:getId*/
	/*AnnColumnAnnotation:getId*/@Column(name = "NEW_ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	/*BasicAnnotation:getHorodatage*/@Temporal(TemporalType.TIMESTAMP)
	/*AnnColumnAnnotation:getHorodatage*/@Column(name = "NEW_HORODATAGE", nullable = false, length = 0)
	public Date getHorodatage() {
		return this.horodatage;
	}

	public void setHorodatage(Date horodatage) {
		this.horodatage = horodatage;
	}

	/*BasicAnnotation:getText*/
	/*AnnColumnAnnotation:getText*/@Column(name = "NEW_TEXT", nullable = false, length = 65535)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

}
