package jkt.centralisateur.storage.model;

// Generated by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Profile generated by hbm2java
 */
@Entity
@Table(name = "profile", catalog = "centralisateur")
public class Profile implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	static public final String _nom = "nom";

	private String nom;

	public Profile() {
	}

	public Profile(String nom) {
		this.nom = nom;
	}

	@Id
	/*BasicAnnotation:getNom*/
	/*AnnColumnAnnotation:getNom*/@Column(name = "PRF_NOM", unique = true, nullable = false, length = 20)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

}
