package jkt.centralisateur.storage.model;

// Generated by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "centralisateur")
public class User implements java.io.Serializable {

	private static final long serialVersionUID = 1L;

	static public final String _id = "id";
	static public final String _login = "login";
	static public final String _password = "password";
	static public final String _email = "email";
	static public final String _profiles = "profiles";
	static public final String _uuidInscription = "uuidInscription";
	static public final String _enabled = "enabled";

	private long id;
	private String login;
	private String password;
	private String email;
	private String uuidInscription;
	private boolean enabled;

    private Set<Profile> profiles = new HashSet<Profile>(0);

	public User() {
	}

	public User(long id, String login, String password, String email, String uuidInscription) {
		this.id = id;
		this.login = login;
		this.password = password;
		this.email = email;
		this.uuidInscription = uuidInscription;
	}

	public User(long id, String login, String password, String email, String uuidInscription,
			Set<Profile> profiles) {
		this.id = id;
		this.login = login;
		this.password = password;
		this.email = email;
		this.profiles = profiles;
		this.uuidInscription = uuidInscription;
	}

	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	/*BasicAnnotation:getId*/
	/*AnnColumnAnnotation:getId*/@Column(name = "USR_ID", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	/*BasicAnnotation:getLogin*/
	/*AnnColumnAnnotation:getLogin*/@Column(name = "USR_LOGIN", nullable = false, length = 20)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	/*BasicAnnotation:getPassword*/
	/*AnnColumnAnnotation:getPassword*/@Column(name = "USR_PASSWORD", nullable = false, length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	/*BasicAnnotation:getEmail*/
	/*AnnColumnAnnotation:getEmail*/@Column(name = "USR_EMAIL", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}
	
	   /*BasicAnnotation:getUuidInscription*/
    /*AnnColumnAnnotation:getUuidInscription*/@Column(name = "USR_UUID_INSCRIPTION", nullable = true, length = 16)
    public String getUuidInscription() {
        return this.uuidInscription;
    }

    public void setUuidInscription(String uuidInscription) {
        this.uuidInscription = uuidInscription;
    }

	/*CollectionAnnotation:getProfiles*/@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "user_profile", catalog = "centralisateur", joinColumns = { @JoinColumn(name = "USR_ID", nullable = false, updatable = true) }, inverseJoinColumns = { @JoinColumn(name = "PRF_NOM", nullable = false, updatable = true) })
	public Set<Profile> getProfiles() {
		return this.profiles;
	}

	public void setProfiles(Set<Profile> profiles) {
		this.profiles = profiles;
	}

	@Column(name = "USR_ENABLED", nullable = false)
	public boolean isEnabled() {
	    return enabled;
	}

	public void setEnabled(boolean enabled) {
	    this.enabled = enabled;
	}

}
